/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mrsdwxswmlhpitdbopsi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yc2R3eHN3bWxocGl0ZGJvcHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzOTIyNjEsImV4cCI6MjA3Njk2ODI2MX0.keyiZqbtUaH-tdIvIS7jXEoUMVUl3-30y0Adu8yK_WM"